# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  database: smjjl
  username: joey
  password: joey
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  database: smjjl
  pool: 5
  username: joey
  password: joey
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: smjjl
  username: joey
  password: joey
  host: localhost
  pool: 2
  timeout: 5000
