:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - [daemon, 10]
  - [update_price, 9]
  - [default, 5]
  - [update_content, 4]
  - [get_pagination, 2]
  - [get_id, 1]

development:
  :concurrency: 5
production:
  :concurrency: 10
worker:
  :concurrency: 20
